In [39]:
import sqlite3
import pandas as pd
con=sqlite3.connect(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\data\raw\ipl.db')

In [40]:
def q(sql):
    return pd.read_sql_query(sql,con)

In [41]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran', path)

In [42]:
q("""
--what is the strike rate of every batter in the death overs

select batter,
round(100.0*sum(batter_runs))/sum(
    case 
        when is_wide_ball=0 and is_no_ball=0 
        then 1
        else 0
    end) as strike_rate

from deliveries
where over_number>=15 and is_super_over=0
group by batter;""")

             batter  strike_rate
0    A Ashish Reddy   146.575342
1          A Badoni   165.030675
2        A Chandila    57.142857
3          A Chopra    50.000000
4       A Choudhary   125.000000
..              ...          ...
637      Yash Dayal    50.000000
638   Yashpal Singh   130.769231
639   Yudhvir Singh   166.666667
640    Yuvraj Singh   183.400810
641          Z Khan   100.000000

[642 rows x 2 columns]

In [43]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\03_venue_names.sql')
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\05_city_fallback.sql')
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\06_season_year.sql')
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\08_matches_clean.sql')
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\09_analysis_views.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\03_venue_names.sql
ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\05_city_fallback.sql
ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\06_season_year.sql
ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\08_matches_clean.sql
ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\09_analysis_views.sql

In [44]:
q(""" select * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [45]:
q("""select count(*)from v_match_totals;""")

   count(*)
0      1187

In [46]:
q("""select count(*) from v_innings ;""")

   count(*)
0      2418

In [47]:
q("""select phase, count(*) from v_ball ;""")

       phase  count(*)
0  Powerplay    288051

In [48]:
q("""

--give the list of highest runs scored in ipl history
--top 5
select batter as player,
sum(batter_runs) as total_runs
from v_ball
group by batter
order by total_runs desc
limit 5;""")

      player  total_runs
0    V Kohli        9040
1  RG Sharma        7183
2   S Dhawan        6769
3  DA Warner        6565
4   KL Rahul        5655

In [49]:
q("""

--give the list of players with highest sixes scored in ipl history
--top 10
select batter as player,
sum(case when batter_runs = 6 then 1 else 0 end) as total_sixes
from v_ball
group by batter
order by total_sixes desc
limit 10;""")

           player  total_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [50]:
q(""" select * from v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [51]:
q("""
--highest ball faced by a player,total,runs,strike rate

select batter,
            sum(is_legal) as balls,
            sum(batter_runs) as runs,
            round(100.0 * sum(batter_runs) / sum(is_legal), 2) as strike_rate

    from v_ball
    group by batter
    order by balls desc
    limit 10;





""")

       batter  balls  runs  strike_rate
0     V Kohli   6730  9040       134.32
1   RG Sharma   5396  7183       133.12
2    S Dhawan   5302  6769       127.67
3   DA Warner   4675  6565       140.43
4   AM Rahane   4141  5194       125.43
5    KL Rahul   4059  5655       139.32
6    SK Raina   4022  5528       137.44
7    MS Dhoni   3935  5439       138.22
8  RV Uthappa   3782  4952       130.94
9  KD Karthik   3567  4842       135.74

In [52]:
q(""" 
--batter who scored the highest share of runs in boundary

select batter,
            sum(batter_runs)as runs,
            round(100.0*(case when batter_runs in (4,6)
            then batter_runs
            else 0
            end)/sum(batter_runs),2) as boundary_perc

from v_ball
group by batter
order by boundary_perc desc
limit 10;""")

                    batter  runs  boundary_perc
0               Auqib Nabi     4          100.0
1                Liton Das     4          100.0
2                 RS Sodhi     4          100.0
3                VRV Singh     4          100.0
4          Arshad Khan (2)     5           80.0
5          KMDN Kulasekara     5           80.0
6            Shivam Sharma     5           80.0
7  JPR Scantlebury-Searles     8           75.0
8                KAJ Roach    10           40.0
9                   SD Lad    15           40.0

In [53]:
q("""select batter,sum(is_legal) as balls, sum(batter_runs) as runs,
        round(100.0* sum(batter_runs)/sum(is_legal),2) as run_rate

from v_ball
where phase = 'Middle'
group by batter
having balls > 500
order by run_rate desc
limit 20;""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062    173.81
1        RM Patidar    566   970    171.38
2          N Pooran    848  1351    159.32
3         H Klaasen    697  1099    157.68
4          CH Gayle   1285  2011    156.50
5        AD Russell    767  1182    154.11
6         SR Watson   1302  2006    154.07
7        GJ Maxwell   1163  1780    153.05
8          SE Marsh    971  1448    149.12
9          DR Smith    675  1004    148.74
10  B Sai Sudharsan    694  1031    148.56
11       JC Buttler   1303  1890    145.05
12         SA Yadav   1845  2664    144.39
13     Shubman Gill   1300  1864    143.38
14       RD Gaikwad    780  1093    140.13
15       MA Agarwal    781  1094    140.08
16          VR Iyer    524   731    139.50
17      YBK Jaiswal    582   811    139.35
18     Ishan Kishan   1091  1518    139.14
19         KL Rahul   1740  2412    138.62

In [54]:
q("""select batter,sum(is_legal) as balls, sum(batter_runs) as runs,
        round(100.0* sum(batter_runs)/sum(is_legal),2) as strike_rate

from v_ball
where phase = 'Middle'
group by batter
having balls > 500
order by strike_rate desc
limit 20;""")

             batter  balls  runs  strike_rate
0          V Sehwag    611  1062       173.81
1        RM Patidar    566   970       171.38
2          N Pooran    848  1351       159.32
3         H Klaasen    697  1099       157.68
4          CH Gayle   1285  2011       156.50
5        AD Russell    767  1182       154.11
6         SR Watson   1302  2006       154.07
7        GJ Maxwell   1163  1780       153.05
8          SE Marsh    971  1448       149.12
9          DR Smith    675  1004       148.74
10  B Sai Sudharsan    694  1031       148.56
11       JC Buttler   1303  1890       145.05
12         SA Yadav   1845  2664       144.39
13     Shubman Gill   1300  1864       143.38
14       RD Gaikwad    780  1093       140.13
15       MA Agarwal    781  1094       140.08
16          VR Iyer    524   731       139.50
17      YBK Jaiswal    582   811       139.35
18     Ishan Kishan   1091  1518       139.14
19         KL Rahul   1740  2412       138.62

In [55]:
# which batter are hardest to bowl a dot ball to in the death overs?

q("""
   SELECT batter,COUNT(*) AS total_balls,
   SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
   ROUND(
        100.0*SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS dot_ball_percentage
FROM v_ball
WHERE phase = 'Death'
  AND is_legal = 1
GROUP BY batter
HAVING total_balls > 500
ORDER BY dot_ball_percentage ASC
LIMIT 10;
""")

           batter  total_balls  dot_balls  dot_ball_percentage
0       JP Duminy          516        104                20.16
1  AB de Villiers          829        175                21.11
2        SK Raina          521        111                21.31
3        KL Rahul          502        110                21.91
4         V Kohli          807        185                22.92
5        DJ Bravo          516        128                24.81
6       AT Rayudu          692        173                25.00
7       DA Miller          835        212                25.39
8        AR Patel          629        162                25.76
9       RA Jadeja         1240        323                26.05

In [56]:
q("""
  --How do runs and wickets differ across the three phases of an innings

SELECT
    phase,
    SUM(total_runs) AS runs,
    SUM(is_wicket) AS wickets
FROM v_ball
GROUP BY phase
ORDER BY phase desc;
    



""")

       phase    runs  wickets
0  Powerplay  116397     3483
1     Middle  169160     5562
2      Death  104056     5264

In [57]:
q("""
  --How do runs and wickets differ across the three phases of an innings

SELECT
    phase,
    SUM(is_legal) AS balls,
    SUM(total_runs) AS runs,
    ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over,
    sum(is_wicket) AS wickets,
    ROUND(100.0*SUM(is_wicket)/SUM(is_legal),2) AS wicket_percentage
FROM v_ball
GROUP BY phase
ORDER BY phase desc;
    



""")

       phase   balls    runs  runs_per_over  wickets  wicket_percentage
0  Powerplay   86921  116397           8.03     3483               4.01
1     Middle  128191  169160           7.92     5562               4.34
2      Death   62205  104056          10.04     5264               8.46

In [58]:
q("""
-- which over of the innings is the most expensive

SELECT
    over_number+1 AS over_number,
    SUM(total_runs) AS runs,
    ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over
FROM v_ball
GROUP BY over_number
ORDER BY runs DESC
LIMIT 20;
""")

    over_number   runs  runs_per_over
0            18  21722          10.12
1            19  21063          10.53
2            17  21001           9.46
3             6  20917           8.68
4             5  20862           8.65
5             4  20842           8.63
6            16  20620           9.05
7            15  20230           8.74
8             3  20219           8.37
9            14  19742           8.43
10           20  19650          11.39
11           13  19273           8.17
12           12  19265           8.13
13           11  18938           7.96
14            9  18626           7.77
15            2  18360           7.60
16           10  18342           7.66
17            8  17953           7.47
18            7  16791           6.98
19            1  15197           6.28

In [59]:
q("""
-- what is the average score at the end of the powerplay

SELECT
    ROUND(AVG(powerplay_runs),2) AS average_powerplay_score
FROM (SELECT match_id,innings,
SUM(total_runs) AS powerplay_runs
FROM v_ball
WHERE phase = 'Powerplay'AND  innings IN(1,2)
GROUP BY match_id, innings
) AS powerplay_scores;
""")

   average_powerplay_score
0                    48.14

In [60]:
q("""
  SELECT over_number +1 AS over_number,
  ROUND(6.0*SUM(is_wicket)/SUM(is_legal),2) AS  wickets_per_over
  FROM v_ball
  GROUP BY over_number
  ORDER BY wickets_per_over DESC;""")

    over_number  wickets_per_over
0            20              0.83
1            19              0.54
2            18              0.49
3            17              0.39
4            16              0.36
5            15              0.33
6            14              0.30
7            13              0.28
8            11              0.27
9             5              0.27
10           12              0.26
11            9              0.25
12            4              0.25
13            3              0.25
14            6              0.24
15           10              0.23
16            2              0.23
17            8              0.22
18            7              0.21
19            1              0.20

In [61]:
q("""
-- Find the most economical bowler

SELECT
    bowler,
    SUM(bowler_runs) AS runs_conceded,
    SUM(is_legal) AS legal_balls,
    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy_rate
FROM v_ball
GROUP BY bowler
HAVING legal_balls > 500
ORDER BY economy_rate ASC
LIMIT 10;
""")

            bowler  runs_conceded  legal_balls  economy_rate
0         A Kumble           1058          965          6.58
1   M Muralitharan           1696         1524          6.68
2       DL Vettori            879          777          6.79
3        SP Narine           5102         4507          6.79
4         DW Steyn           2508         2176          6.92
5          J Botha            800          694          6.92
6         R Sharma           1086          928          7.02
7  Harbhajan Singh           4030         3416          7.08
8       SL Malinga           3366         2827          7.14
9      Rashid Khan           4040         3387          7.16

In [62]:
q("""
-- Which bowler bowls the most dot balls?
-- bowler, balls, dot_ball, dot_perc

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_ball,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS dot_perc
FROM v_ball
WHERE is_legal = 1
GROUP BY bowler
HAVING balls > 500
ORDER BY dot_ball DESC
LIMIT 10;
""")

            bowler  balls  dot_ball  dot_perc
0          B Kumar   4432      1935     43.66
1        SP Narine   4507      1788     39.67
2         R Ashwin   4710      1663     35.31
3        JJ Bumrah   3517      1485     42.22
4        RA Jadeja   4188      1379     32.93
5        PP Chawla   3850      1358     35.27
6        YS Chahal   3941      1353     34.33
7  Harbhajan Singh   3416      1312     38.41
8      Rashid Khan   3387      1270     37.50
9         UT Yadav   3050      1260     41.31

In [63]:
q("""
-- How do bowlers actually take their wickets?

SELECT wicket_kind, COUNT(*) AS n
FROM v_ball
WHERE is_wicket = 1
GROUP BY wicket_kind
ORDER BY n DESC
;
""")

             wicket_kind     n
0                 caught  9045
1                 bowled  2398
2                run out  1167
3                    lbw   871
4      caught and bowled   399
5                stumped   382
6           retired hurt    19
7             hit wicket    18
8            retired out     6
9  obstructing the field     4

In [64]:
q("""SELECT CASE WHEN bowler_type LIKE                      
       '%Legbreak%' OR bowler_type LIKE 
       '%Offbreak%' OR bowler_type LIKE 
       '%Orthodox%' OR bowler_type LIKE 
       '%Wrist spin%' OR bowler_type LIKE 
       '%Googly%' THEN 'Spin' ELSE 'Pace' 
       END AS style,                                  
       SUM(is_legal) AS balls,                           
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)       
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  
              AS wicket_pct 
FROM   v_ball                                          
WHERE  bowler_type IS NOT NULL AND                      
       TRIM(bowler_type) <> '' 
GROUP  BY style;""")

  style   balls  economy  wicket_pct
0  Pace  176859     8.57        4.93
1  Spin  100129     7.76        4.37

In [65]:
q("""SELECT CASE WHEN bowler_type LIKE 'Left%'             
       THEN 'Left arm' ELSE 'Right arm' END             
       AS arm, 
       batsman_type, 
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)     
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  
              AS wicket_pct 
FROM   v_ball                                         
WHERE  TRIM(COALESCE(bowler_type,'')) <> ''           
       AND batsman_type IS NOT NULL                   
GROUP  BY arm, batsman_type;""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [66]:
q("""
-- Which spinner is the best wicket-taker?

SELECT
    bowler,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE bowler_type LIKE '%Legbreak%'
   OR bowler_type LIKE '%Offbreak%'
   OR bowler_type LIKE '%Orthodox%'
   OR bowler_type LIKE '%Wrist spin%'
   OR bowler_type LIKE '%Googly%'
GROUP BY bowler
HAVING SUM(is_legal) > 500
ORDER BY wicket DESC
LIMIT 10;
""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [67]:
q("""
-- We need a powerplay strike bowler
-- Who takes most wickets in overs 1 to 6

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE over_number BETWEEN 0 AND 5
  AND is_legal = 1
GROUP BY bowler
HAVING balls > 300
ORDER BY wicket DESC
LIMIT 10;
""")

           bowler  balls  wicket  wicket_perc
0         B Kumar   2453      89         3.63
1        TA Boult   1644      72         4.38
2       DL Chahar   1527      67         4.39
3  Sandeep Sharma   1728      64         3.70
4        UT Yadav   1446      58         4.01
5        I Sharma   1521      57         3.75
6  Mohammed Shami   1584      57         3.60
7          Z Khan   1292      52         4.02
8  Mohammed Siraj   1326      50         3.77
9        R Ashwin   1252      48         3.83

In [68]:
q("""

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS wicket,
    ROUND(
            100.0 * SUM(bowler_wicket) / SUM(is_legal),
            2
        ) AS wicket_perc
FROM v_ball
WHERE phase='Powerplay'
GROUP BY bowler
    HAVING total_balls>300
    ORDER BY wicket DESC;""")

            bowler  total_balls  wicket  wicket_perc
0          B Kumar         2453      89         3.63
1         TA Boult         1644      72         4.38
2        DL Chahar         1527      67         4.39
3   Sandeep Sharma         1728      64         3.70
4         UT Yadav         1446      58         4.01
..             ...          ...     ...          ...
75    DE Bollinger          324      11         3.40
76    Mukesh Kumar          354      11         3.11
77       SM Curran          570      11         1.93
78    M Theekshana          312      10         3.21
79       JO Holder          354       9         2.54

[80 rows x 4 columns]

In [69]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(is_legal AND total_runs = 0) AS dot_balls,
    ROUND(100.0 * SUM(is_legal AND total_runs = 0) / SUM(is_legal), 2) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING balls >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [70]:
run_sql_file(r'C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\08_matches_clean.sql')

ran C:\Users\ubaid\OneDrive\Desktop\sem-3\project 3.1\sql\practice\08_matches_clean.sql

In [71]:
q("""
-- What do captains actually choose when they win the toss?
-- toss_decision, total_count, perc

SELECT
    toss_decision,
    COUNT(*) AS total_count,
    ROUND(
        100.0 * COUNT(*) / (SELECT COUNT(*) FROM matches_clean),
        2
    ) AS perc
FROM  matches_clean
GROUP BY toss_decision;
""")

  toss_decision  total_count   perc
0           bat          412  33.99
1         field          800  66.01

In [72]:
q("""select count(*) from matches_clean;""")

   count(*)
0      1212

In [73]:
q("""
SELECT
    match_winner AS team,
    COUNT(*) AS wins
FROM matches_clean
WHERE result = 'win'
GROUP BY match_winner
ORDER BY wins DESC
;
""")

                           team  wins
0                Mumbai Indians   153
1           Chennai Super Kings   145
2   Royal Challengers Bangalore   138
3         Kolkata Knight Riders   136
4           Sunrisers Hyderabad   128
5                  Punjab Kings   125
6                Delhi Capitals   122
7              Rajasthan Royals   120
8                Gujarat Titans    42
9          Lucknow Super Giants    32
10       Rising Pune Supergiant    15
11                Gujarat Lions    13
12                Pune Warriors    12
13         Kochi Tuskers Kerala     6

In [74]:
q("""
SELECT
    batting_team AS team,
    SUM(total_runs) AS powerplay_runs,
    SUM(is_legal) AS legal_balls,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batting_team
HAVING legal_balls > 3000
ORDER BY run_rate DESC;
""")

                          team  powerplay_runs  legal_balls  run_rate
0                 Punjab Kings           13344         9755      8.21
1          Sunrisers Hyderabad           13712        10034      8.20
2             Rajasthan Royals           11797         8768      8.07
3               Delhi Capitals           13237         9893      8.03
4        Kolkata Knight Riders           13016         9738      8.02
5               Mumbai Indians           13561        10257      7.93
6  Royal Challengers Bangalore           13196        10008      7.91
7          Chennai Super Kings           12198         9324      7.85

In [75]:
q(""" select batting_team,
round(6.0*sum(total_runs)/sum(is_legal),2) as run_rate
from v_ball
where phase = 'Powerplay'
group by batting_team
having sum(is_legal) > 3000
order by run_rate desc limit 10;""")

                  batting_team  run_rate
0                 Punjab Kings      8.21
1          Sunrisers Hyderabad      8.20
2             Rajasthan Royals      8.07
3               Delhi Capitals      8.03
4        Kolkata Knight Riders      8.02
5               Mumbai Indians      7.93
6  Royal Challengers Bangalore      7.91
7          Chennai Super Kings      7.85

In [ ]:
q("""
SELECT
    batting_team,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN batter_runs IN (4, 6) THEN batter_runs
                ELSE 0
            END
        ) / NULLIF(SUM(batter_runs), 0),
        2
    ) AS boundary_run_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >= 10000
ORDER BY boundary_run_percentage DESC;
""")

DatabaseError: Execution failed on sql 'SELECT
    batting_team,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN batter_runs IN (4, 6) THEN batter_runs
                ELSE 0
            END) / SUM(batter_runs),2) AS boundary_run_percentage
FROM deliveries
GROUP BY batting_team
HAVING SUM(is_legal) >= 10000
ORDER BY boundary_run_percentage DESC;': no such column: is_legal